## **PANDAS**

* Introduction to Pandas library which is one of the important library for data analytics. We'll cover what is a dataframe and series.
* Data Manipulation with Pandas.
* We will explore various functions available in the Pandas library.

## **Introduction to Pandas**<a name="pandas"></a>

* Pandas is a Python library which is primarily used for tabular data manipulation and analysis.
* Specifically, it provides us with data structures called as Series and DataFrames.
* The name Pandas is derived from the word Panel Data – an Econometrics from Multidimensional data.
* Pandas internally uses NumPy for storing the data efficiently.

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
type(pd)

module

In [3]:
# Check Pandas version

print(pd.__version__)

2.2.3

## **Dataframe and Series** <a name="data-frame-series"></a>

* A series is essentially a column and dataframe is a multi-dimensional table made up of collection of series.

In [4]:
# Creating pandas series
cars =  ['Comet', 'Tiago', 'i20']

series = pd.Series(data=cars)

print(series)
print(f"Type of series: {type(series)}")

0    Comet
1    Tiago
2      i20
dtype: object
Type of series: <class 'pandas.core.series.Series'>

In [4]:
#Creating pandas dataframe
df = pd.DataFrame({'cars': ['Comet', 'Tiago', 'i20'],
                    'Brands': ['MG', 'Tata', 'Hyundai'],
                    'Age': [2, 7, 9]})

print(df)
print(f"Type of df: {type(df)}")

    cars   Brands  Age
0  Comet       MG    2
1  Tiago     Tata    7
2    i20  Hyundai    9
Type of df: <class 'pandas.core.frame.DataFrame'>

## **How to read files of different format** <a name="read-csv-files"></a>

In [18]:
#from google.colab import drive
#drive.mount('/content/drive')
import os
from pathlib import Path
base_dir = Path.cwd()
file_path = os.path.join(base_dir, "DATA", "Iris_data_sample.csv")
print(file_path)
# sep='/t' is used as the csv file is seperated with a tab spacing

c:\MyProjects\DataAnalysis\DATA\Iris_data_sample.csv

#### **Reading .csv format data**

In [8]:
data_csv = pd.read_csv(file_path)
#data_csv = pd.read_csv('/content/drive/MyDrive/Datasets/Iris_data_sample.csv')
data_csv.head(10)

,Unnamed: 0,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,NaN,1.4,0.2,NaN
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,??,3.1,1.5,0.2,Iris-setosa
4,5,5,3.6,###,0.2,Iris-setosa
5,6,5.4,3.9,NaN,0.4,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
7,8,5,3.4,1.5,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa

In [9]:
# =============================================================================
# Setting the 1st coulmn 'Unnamed: 0' as index column while reading data
# =============================================================================
data_csv = pd.read_csv(file_path,index_col=0)
#data_csv = pd.read_csv('/content/drive/MyDrive/Datasets/Iris_data_sample.csv',index_col=0)
data_csv.head()

  SepalLengthCm  SepalWidthCm PetalLengthCm  PetalWidthCm      Species
1           5.1           3.5           1.4           0.2  Iris-setosa
2           4.9           NaN           1.4           0.2          NaN
3           4.7           3.2           1.3           0.2  Iris-setosa
4            ??           3.1           1.5           0.2  Iris-setosa
5             5           3.6           ###           0.2  Iris-setosa

In [11]:
# =============================================================================
# Replacing ‘??’ and ‘# # #’ as 'nan' values
# =============================================================================
data_csv = pd.read_csv(file_path,index_col=0,na_values=["??"])
'''data_csv = pd.read_csv('/content/drive/MyDrive/Datasets/Iris_data_sample.csv',
                       index_col=0,na_values=["??"])

data_csv = pd.read_csv('/content/drive/MyDrive/Datasets/Iris_data_sample.csv',
                       index_col=0,na_values=["??","###"])
'''
data_csv = pd.read_csv(file_path,index_col=0,na_values=["??","###"])
data_csv.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1            5.1           3.5            1.4           0.2  Iris-setosa
2            4.9           NaN            1.4           0.2          NaN
3            4.7           3.2            1.3           0.2  Iris-setosa
4            NaN           3.1            1.5           0.2  Iris-setosa
5            5.0           3.6            NaN           0.2  Iris-setosa

#### **Reading .xlsx format data**

In [ ]:
data_xlsx = pd.read_excel('c:/MyProjects/DataAnalysis/DATA/Iris_data_sample.xlsx',
                        sheet_name='Iris_data')

data_xlsx = pd.read_excel('c:/MyProjects/DataAnalysis/DATA/Iris_data_sample.xlsx',index_col=0)

data_xlsx = pd.read_excel('c:/MyProjects/DataAnalysis/DATA/Iris_data_sample.xlsx',
                        index_col=0,
                        na_values=["??","###"])

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1            5.1           3.5            1.4           0.2  Iris-setosa
2            4.9           NaN            1.4           0.2          NaN
3            4.7           3.2            1.3           0.2  Iris-setosa
4            NaN           3.1            1.5           0.2  Iris-setosa
5            5.0           3.6            NaN           0.2  Iris-setosa

In [27]:
data_xlsx.head(6)

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1            5.1           3.5            1.4           0.2  Iris-setosa
2            4.9           NaN            1.4           0.2          NaN
3            4.7           3.2            1.3           0.2  Iris-setosa
4            NaN           3.1            1.5           0.2  Iris-setosa
5            5.0           3.6            NaN           0.2  Iris-setosa
6            5.4           3.9            NaN           0.4  Iris-setosa

#### **Reading .txt format data**


 - Delimitor can be a space or a tab               
 - Try out to see what works

In [ ]:

#Instead of using read_table(), read_csv() can also be used to read .txt files
data_txt1 = pd.read_csv('/content/drive/MyDrive/Datasets/Iris_data_sample.txt',delimiter=" ")
data_txt1.head()

# Toyota cars - case study

In [ ]:
# =============================================================================
# Importing data
# =============================================================================
# By passing 'index_col=0', first column becomes the index column
cars_data = pd.read_csv('/content/drive/MyDrive/Datasets/Toyota.csv', index_col=0)

In [ ]:
# =============================================================================
# Creating copy of original data
# =============================================================================
'''
In Python, there are two ways to create copies
 * Shallow copy :
 - It only creates a new variable that shares the reference of the original object
 - Any changes made to a copy of object will be reflected in the original object as well
 * Deep copy:
 - In case of deep copy, a copy of object is copied in other object with no
   reference to the original
 - Any changes made to a copy of object will not be reflected in the original object
'''
# shallow copy
samp = cars_data
samp = cars_data.copy(deep=False)

# deep copy
cars_data1 = cars_data.copy()
cars_data1 = cars_data.copy(deep=True)

In [ ]:

# =============================================================================
# Attributes of data
# =============================================================================
cars_data1.index         # to get the index (row labels) of the dataframe
cars_data1.columns       # to get the column labels of the dataframe
cars_data1.size          # to get the total number of elements from the dataframe
cars_data1.shape         # to get the dimensionality of the dataframe
cars_data1.memory_usage()# to get the memory usage of each column in bytes
cars_data1.ndim          # to get the number of axes / array dimensions
                         # a two-dimensional array stores data in a format
                         # consisting of rows and columns

In [ ]:
cars_data1.index

In [ ]:
cars_data1.columns

In [ ]:
cars_data1.size

In [ ]:
cars_data1.shape

In [ ]:
cars_data1.memory_usage()

In [ ]:
cars_data1.ndim

In [ ]:
# =============================================================================
# Indexing and selecting data
# =============================================================================
"""
 - Python slicing operator ‘[ ]’ and attribute/ dot operator ‘. ’  are used
   for indexing
 - Provides quick and easy access to pandas data structures
"""
cars_data1.head(6) # The function head returns the first n rows from the dataframe
                   # By default, the head() returns first 5 rows

In [ ]:
cars_data1.tail(5) # The function tail returns the last n rows
                   # for the object based on position

In [ ]:
"""
 -  To access a scalar value, the fastest way is to use the 'at' and 'iat' methods
 - 'at' provides label-based scalar lookups
 - 'iat' provides integer-based lookups
"""
cars_data1.at[4,'FuelType'] # value corresponds to 5th row & 'FuelType' column

In [ ]:
cars_data1.iat[5,6]         # value corresponds to 6th row & 7th column

In [ ]:

"""
    To access a group of rows and columns by label(s) .loc[ ] can be used
"""
cars_data1.loc[:,'FuelType']

# Data types

    - The way information gets stored in a dataframe or a python object affects
      the analysis and outputs of calculations
    - There are two main types of data : numeric and character types
    - Numeric data types includes integers and floats
    - For example: integer – 10, float – 10.53    
    - Strings are known as objects in pandas which can store values that contain
    - numbers and / or characters
    - For example: ‘category1’

In [ ]:
# =============================================================================
# Checking data types of each column
# =============================================================================
cars_data1.dtypes             # returns a series with the data type of each column

In [ ]:
# =============================================================================
# Count of Unique Data Types
# =============================================================================

cars_data1.dtypes.value_counts()

In [ ]:
# =============================================================================
# Selecting data based on data types
# =============================================================================
cars_data1.select_dtypes(exclude=[object])
# returns a subset of the columns from dataframe by excluding columns of object data

# Concise summary of dataframe

info():

returns a concise summary of a dataframe

    - data type of index
    - data type of columns
    - count of non-null values

In [ ]:
cars_data1.info()

# Checking format of each column

By using info(), we can see
    
    - ‘KM’ has been read as object instead of integer
    
    - ‘HP’ has been read as object instead of integer
    
    - ‘MetColor’ and ‘Automatic’ have been read as float64 and int64 respectively
    
       since it has values 0/1
    
    - Ideally, ‘Doors’ should’ve been read as int64 since it has values 2, 3, 4, 5.
    
      But it has been read as object
    
    - Missing values present in few variables

Let’s encounter the reason !

 Unique elements of columns:
 unique() is used to find the unique elements of a column """

In [ ]:
print(np.unique(cars_data1['KM'])) # ‘KM’ has special character to it '??'
                                   # Hence, it has been read as object instead of int64

In [ ]:

print(np.unique(cars_data1['HP'])) # ‘HP’ has special character to it '????'
                                   # Hence, it has been read as object instead of int64

In [ ]:


print(np.unique(cars_data1['MetColor'])) # ‘MetColor’ have been read as float64
                                         #  since it has values 0. & 1.

In [ ]:
print(np.unique(cars_data1['Automatic']))# ‘Automatic’ has been read as int64
                                         #  since it has values 0 & 1

In [ ]:

print(np.unique(cars_data1['Doors']))    # ‘Doors’ has been read as object
                                         # instead of int64 because of values
                                         # ‘five’ ‘four’ ‘three’ which are strings


### Importing data (replacing special chars with nan values)

    - We need to know how missing values are represented in the dataset
      in order to make reasonable decisions
    - The missing values exist in the form of ‘nan’, '??', '????'
    - Python, by default replace blank values with ‘nan’
    - Now, importing the data considering other forms of missing values in a dataframe

In [ ]:
cars_data = pd.read_csv('/content/drive/MyDrive/Datasets/Toyota.csv', index_col=0, na_values=["??","????"])

In [ ]:
cars_data.info() # Summary - after replacing special characters with nan

### Converting variable’s data types

In [ ]:

""" astype() method is used to explicitly convert data types from one to another"""

# Converting ‘MetColor’ , ‘Automatic’ to object data type

cars_data['MetColor']  = cars_data['MetColor'].astype('object')
cars_data['Automatic'] = cars_data['Automatic'].astype('object')

In [ ]:

# If ‘FuelType’ is of object data type,
cars_data['FuelType'].nbytes                     # 11488

In [ ]:
# =============================================================================
# category vs object data type
# =============================================================================
""" nbytes() is used to get the total bytes consumed by the elements of the columns"""

# If ‘FuelType’ is of category data type,
cars_data['FuelType'].astype('category').nbytes # 1460

In [ ]:

# Re-checking the data type of variables after all the conversions
cars_data.info()

In [ ]:
# =============================================================================
# Cleaning column ‘Doors’
# =============================================================================
# Checking unique values of variable ‘Doors’ :
print(np.unique(cars_data['Doors']))

"""
    replace() is used to replace a value with the desired value
    Syntax: DataFrame.replace([to_replace, value, …])
"""

cars_data['Doors'].replace('three',3,inplace=True)
cars_data['Doors'].replace('four',4,inplace=True)
cars_data['Doors'].replace('five',5,inplace=True)

In [ ]:
# To check the frequencies of unique cateogories in a variable
cars_data['Doors'].value_counts()

In [ ]:

"""
   (or) Pandas- where()
"""
cars_data['Doors'].where(cars_data['Doors']!='three',3,inplace=True)

In [ ]:
"""
   (or) Numpy- where()
"""
cars_data['Doors'] = np.where(cars_data['Doors']=='five',5,cars_data['Doors'])

# Converting ‘Doors’ to int64:
cars_data['Doors'] = cars_data['Doors'].astype('int64')
cars_data['Doors'].value_counts()

### Cross tables & Correlation

   pandas.crosstab()

    - To compute a simple cross-tabulation of one, two (or more) factors
    - By default computes a frequency table of the factors

In [ ]:
cars_data2 = cars_data.copy()

**One-way table**

In [ ]:
pd.crosstab(index=cars_data2['FuelType'], columns='count', dropna=True)

 Most of the cars have petrol as fuel type

**Two-way table**

To look at the frequency distribution of gearbox types with respect to different fuel types of the cars

In [ ]:
pd.crosstab(index   = cars_data2['Automatic'],
            columns = cars_data2['FuelType'],
            dropna  = True)

**Two-way table with proportion / Joint probability**

Joint probability is the likelihood of two independent events happening at the same time

In [ ]:
pd.crosstab(index     = cars_data2['Automatic'],
            columns   = cars_data2['FuelType'],
            normalize = True,
            dropna    = True)

0.82 => Joint probability of manual gear box and petrol fuel type

**Two-way table - Marginal probability**

Marginal probability is the probability of the occurrence of the single event

In [ ]:
pd.crosstab(index     = cars_data2['Automatic'],
            columns   = cars_data2['FuelType'],
            margins   = True,
            dropna    = True,
            normalize = True)

Probability of cars having manual gear box when the fuel type are
CNG or Diesel or Petrol is 0.95

**Two-way table - Conditional probability=> Row sum = 1**




Conditional probability is the probability of an event ( A ), given that
another event ( B ) has already occurred

In [ ]:
pd.crosstab(index     = cars_data2['Automatic'],
            columns   = cars_data2['FuelType'],
            margins   = True,
            dropna    = True,
            normalize = 'index')

# Given the gear box, probability of different fuel type

**Two-way table - Conditional probability => Column sum =1**

In [ ]:
pd.crosstab(index     = cars_data2['Automatic'],
            columns   = cars_data2['FuelType'],
            margins   = True,
            dropna    = True,
            normalize = 'columns')

# Given the fuel type, probability of different gear box

   
### Correlation    
Correlation: the strength of association between two variables

In [ ]:
# Excluding the categorical variables to find the correlation

numerical_data = cars_data2.select_dtypes(exclude=[object])
print(numerical_data.shape)

# Finding the correlation between numerical variables
corr_matrix = numerical_data.corr()
print(corr_matrix)

In [ ]:

# Rounding off to two decimal places
print(round(corr_matrix,2))

### Identifying missing values

 - In Pandas dataframes, missing data is represented by NaN
  (an acronym for Not a Number)
 - To check null values in Pandas dataframes, isnull() and isna() are used
 - These functions returns a dataframe of Boolean values which are True for NaN values

In [ ]:
cars_data2 = cars_data.copy()
cars_data3 = cars_data2.copy()

In [ ]:
# To check the count of missing values present in each column

print('Data columns with null values:\n')
cars_data2.isna().sum()   #or

Data columns with null values:

Price          0
Age          100
KM            15
FuelType     100
HP             6
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

In [ ]:
cars_data2.isnull().sum()

Price          0
Age          100
KM            15
FuelType     100
HP             6
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

In [ ]:
# Subsetting the rows that have one or more missing values
missing = cars_data2[cars_data2.isnull().any(axis=1)]
missing

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
2,13950,24.0,41711.0,Diesel,90.0,NaN,0,2000,3,1165
6,16900,27.0,NaN,Diesel,NaN,NaN,0,2000,3,1245
7,18600,30.0,75889.0,NaN,90.0,1.0,0,2000,3,1245
9,12950,23.0,71138.0,Diesel,NaN,NaN,0,1900,3,1105
15,22000,28.0,18739.0,Petrol,NaN,0.0,0,1800,3,1185
...,...,...,...,...,...,...,...,...,...,...
1428,8450,72.0,NaN,Petrol,86.0,NaN,0,1300,3,1015
1431,7500,NaN,20544.0,Petrol,86.0,1.0,0,1300,3,1025
1432,10845,72.0,NaN,Petrol,86.0,0.0,0,1300,3,1015
1433,8500,NaN,17016.0,Petrol,86.0,0.0,0,1300,3,1015
1434,7250,70.0,NaN,NaN,86.0,1.0,0,1300,3,1015


### Imputing missing values

Explore Distributions:

In [ ]:
cars_data2.describe()

,Price,Age,KM,HP,CC,Doors,Weight
count,1436.000000,1336.000000,1421.000000,1430.000000,1436.000000,1436.000000,1436.00000
mean,10730.824513,55.672156,68647.239972,101.478322,1566.827994,4.033426,1072.45961
std,3626.964585,18.589804,37333.023589,14.768255,187.182436,0.952677,52.64112
min,4350.000000,1.000000,1.000000,69.000000,1300.000000,2.000000,1000.00000
25%,8450.000000,43.000000,43210.000000,90.000000,1400.000000,3.000000,1040.00000
50%,9900.000000,60.000000,63634.000000,110.000000,1600.000000,4.000000,1070.00000
75%,11950.000000,70.000000,87000.000000,110.000000,1600.000000,5.000000,1085.00000
max,32500.000000,80.000000,243000.000000,192.000000,2000.000000,5.000000,1615.00000

In [ ]:
cars_data2.describe(include="O")

       FuelType  MetColor  Automatic
count      1336    1286.0       1436
unique        3       2.0          2
top      Petrol       1.0          0
freq       1177     868.0       1356

In [ ]:
cars_data2.describe(include="all")

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
count,1436.000000,1336.000000,1421.000000,1336,1430.000000,1286.0,1436.0,1436.000000,1436.000000,1436.00000
unique,NaN,NaN,NaN,3,NaN,2.0,2.0,NaN,NaN,NaN
top,NaN,NaN,NaN,Petrol,NaN,1.0,0.0,NaN,NaN,NaN
freq,NaN,NaN,NaN,1177,NaN,868.0,1356.0,NaN,NaN,NaN
mean,10730.824513,55.672156,68647.239972,NaN,101.478322,NaN,NaN,1566.827994,4.033426,1072.45961
std,3626.964585,18.589804,37333.023589,NaN,14.768255,NaN,NaN,187.182436,0.952677,52.64112
min,4350.000000,1.000000,1.000000,NaN,69.000000,NaN,NaN,1300.000000,2.000000,1000.00000
25%,8450.000000,43.000000,43210.000000,NaN,90.000000,NaN,NaN,1400.000000,3.000000,1040.00000
50%,9900.000000,60.000000,63634.000000,NaN,110.000000,NaN,NaN,1600.000000,4.000000,1070.00000
75%,11950.000000,70.000000,87000.000000,NaN,110.000000,NaN,NaN,1600.000000,5.000000,1085.00000
max,32500.000000,80.000000,243000.000000,NaN,192.000000,NaN,NaN,2000.000000,5.000000,1615.00000

In [ ]:
# Inspect distributions to guide method choice
desc = cars_data2.describe(include="number").T
skew = cars_data2.select_dtypes(include=["int64", "float64"]).skew(numeric_only=True).to_frame("skew")
desc.join(skew, how="left")

In [ ]:
# Audit missingness
# Calculate the percentage of missing values for each column
missing_pct = (cars_data2.isnull().sum() / len(cars_data2)) * 100

# Create a DataFrame to display the missing counts and percentages
missing_report = pd.DataFrame({
    'missing_count': cars_data2.isnull().sum(),
    'missing_pct': missing_pct
})

# Display the report
display(missing_report)

In [ ]:
cars_data2['KM'].isnull().sum()

### Replacing 'Age' with mean

In [ ]:
# Step 1: Calculate overall median (fallback)
overall_age_median = cars_data2['Age'].median()
overall_age_median

In [ ]:
# Step 2: Create a mapping of FuelType → median Age
fueltype_age_medians = cars_data2.groupby('FuelType')['Age'].median()
fueltype_age_medians

In [ ]:
# Step 3: Fill missing Age by mapping FuelType-specific medians
cars_data2['Age'] = cars_data2['Age'].fillna(
    cars_data2['FuelType'].map(fueltype_age_medians)
)

# Step 4: Fill any remaining with overall median
cars_data2['Age'] = cars_data2['Age'].fillna(overall_age_median)

In [ ]:
# Step 1: Calculate overall median (fallback)
overall_age_median = cars_data2['Age'].median()

# Step 2: Create a mapping of FuelType → median Age
fueltype_age_medians = cars_data2.groupby('FuelType')['Age'].median()

# Step 3: Fill missing Age by mapping FuelType-specific medians
cars_data2['Age'] = cars_data2['Age'].fillna(
    cars_data2['FuelType'].map(fueltype_age_medians)
)

# Step 4: Fill any remaining with overall median
cars_data2['Age'] = cars_data2['Age'].fillna(overall_age_median)

In [ ]:
cars_data2['Age'].isnull().sum()

### Replacing 'KM' with median

In [ ]:
cars_data2['KM'].median()

In [ ]:
cars_data2['KM'].fillna(cars_data2['KM'].median(), inplace = True)

### Replacing 'HP' with mean

In [ ]:
cars_data2['HP'].mean()

cars_data2['HP'].fillna(cars_data2['HP'].mean(), inplace = True)

cars_data2['HP'].isnull().sum()

In [ ]:
# Check for missing data after filling values
cars_data2.isnull().sum()

### Replacing 'Fuel Type' with mode

- Returns a Series containing counts of unique values
- The values will be in descending order so that the first element is
  the most frequently-occurring element
- Excludes NA values by default

In [ ]:
cars_data2['FuelType'].value_counts()

In [ ]:
# To get the mode value of FuelType
cars_data2['FuelType'].value_counts().index[0]

In [ ]:
# To fill NA/NaN values using the specified value
cars_data2['FuelType'].fillna(cars_data2['FuelType']\
      .value_counts().index[0],\
      inplace = True)

In [ ]:
cars_data2['FuelType'].isnull().sum()

###  Replacing 'MetColor' with mode

In [ ]:
# To get the mode value of Metcolor
cars_data2['MetColor'].mode()

In [ ]:
# To get categroy with maximum freq
# Index 0 will get the category
cars_data2['MetColor'].mode()[0]

In [ ]:
# replacing MetColor with mode
cars_data2['MetColor'].fillna(cars_data2['MetColor']\
      .mode()[0], inplace = True)

## Check for missing data after filling values
cars_data2['MetColor'].isnull().sum()

In [ ]:
# Check for missing data after filling values
cars_data2.isnull().sum()


### Imputation using lambda functions

 To fill the NA/ NaN values in both numerical and categorial variables at one stretch

In [ ]:
cars_data3.isnull().sum()

In [ ]:
cars_data3 = cars_data3.apply(
    lambda col: col.fillna(
        cars_data3.groupby('fuel_type')['age'].transform('median')
    ) if col.name == 'age'
    else (
        col.fillna(col.mean()) if pd.api.types.is_numeric_dtype(col)
        else col.fillna(col.mode()[0])
    )
)

print('Data columns with null values:\n', cars_data3.isnull().sum())